name: Docker Build

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_a42f733555e54743b265c63a6cc22c81 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_090f503c013a4bbc8fcb24d92c3e571d }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.docker.io/locajk/nextjs-fastapi:${{ github.sha }}
          file: ./Dockerfile
          
      - name: Verify Docker image
        run: docker images
